# Validates that the pull request branch will build
name: validate-pull-gatsby

# Fires on pull-request to gatsby branc
on:
  pull_request:
    branches: 
      - gatsby

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner on which this job will run
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # - Checkout gatsby branch
    # - Update authentication for Github Package Registry @kenjdavidson/base16-scss
    # - Build gh-pages using action
    steps:
      - uses: actions/checkout@v1
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Node Dependencies
        run: npm install
      - name: Build Gatsby Site
        uses: kenjdavidson/gatsby-cli-github-action@feature/pkg-manager-selection
        env:
          PKG_MANAGER: "npm"
        with:
          gatsby-arg: build
